/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_psmoveapi_csharp(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_psmoveapi_csharp(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else



 /**
 * PS Move API - An interface for the PS Move Motion Controller
 * Copyright (c) 2011, 2012 Thomas Perl <m@thp.io>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 **/


#include "psmove.h"
#include "psmove_tracker.h"
#include "psmove_fusion.h"


SWIGINTERN PSMove *new_PSMove__SWIG_0(){
        return psmove_connect_by_id(0);
    }
SWIGINTERN PSMove *new_PSMove__SWIG_1(int id){
        return psmove_connect_by_id(id);
    }
SWIGINTERN void PSMove_enable_orientation(PSMove *self,int enabled){
        psmove_enable_orientation(self, enabled);
    }
SWIGINTERN int PSMove_has_orientation(PSMove *self){
        return psmove_has_orientation(self);
    }
SWIGINTERN int PSMove_has_calibration(PSMove *self){
        return psmove_has_calibration(self);
    }
SWIGINTERN void PSMove_reset_orientation(PSMove *self){
        psmove_reset_orientation(self);
    }
SWIGINTERN void PSMove_set_leds(PSMove *self,int r,int g,int b){
        psmove_set_leds(self, r, g, b);
    }
SWIGINTERN void PSMove_set_rumble(PSMove *self,int rumble){
        psmove_set_rumble(self, rumble);
    }
SWIGINTERN int PSMove_update_leds(PSMove *self){
        return psmove_update_leds(self);
    }
SWIGINTERN void PSMove_set_rate_limiting(PSMove *self,int enabled){
        psmove_set_rate_limiting(self, enabled);
    }
SWIGINTERN int PSMove_pair(PSMove *self){
        return psmove_pair(self);
    }
SWIGINTERN int PSMove_pair_custom(PSMove *self,char const *btaddr){
        return psmove_pair_custom(self, btaddr);
    }
SWIGINTERN char const *PSMove_get_serial(PSMove *self){
        static char *result = NULL;
        if (result != NULL) {
            free(result);
        }
        result = psmove_get_serial(self);
        return result;
    }
SWIGINTERN int PSMove_is_remote(PSMove *self){
        return psmove_is_remote(self);
    }
SWIGINTERN int PSMove_poll(PSMove *self){
        return psmove_poll(self);
    }
SWIGINTERN int PSMove_get_buttons(PSMove *self){
        return psmove_get_buttons(self);
    }
SWIGINTERN int PSMove_get_battery(PSMove *self){
        return psmove_get_battery(self);
    }
SWIGINTERN int PSMove_get_temperature(PSMove *self){
        return psmove_get_temperature(self);
    }
SWIGINTERN float PSMove_get_temperature_in_celsius(PSMove *self){
        return psmove_get_temperature_in_celsius(self);
    }
SWIGINTERN int PSMove_get_trigger(PSMove *self){
        return psmove_get_trigger(self);
    }
SWIGINTERN void delete_PSMove(PSMove *self){
        psmove_disconnect(self);
    }
SWIGINTERN float PSMoveMatrix4x4_at(PSMoveMatrix4x4 *self,int i){
        return self->m[i];
    }
SWIGINTERN PSMoveTracker *new_PSMoveTracker__SWIG_0(){
        return psmove_tracker_new();
    }
SWIGINTERN PSMoveTracker *new_PSMoveTracker__SWIG_1(int camera){
        return psmove_tracker_new_with_camera(camera);
    }
SWIGINTERN enum PSMoveTracker_Status PSMoveTracker_enable(PSMoveTracker *self,PSMove *move){
        return psmove_tracker_enable(self, move);
    }
SWIGINTERN enum PSMoveTracker_Status PSMoveTracker_enable_with_color(PSMoveTracker *self,PSMove *move,int r,int g,int b){
        return psmove_tracker_enable_with_color(self, move, r, g, b);
    }
SWIGINTERN void PSMoveTracker_annotate(PSMoveTracker *self){
        psmove_tracker_annotate(self);
    }
SWIGINTERN void PSMoveTracker_disable(PSMoveTracker *self,PSMove *move){
        psmove_tracker_disable(self, move);
    }
SWIGINTERN void PSMoveTracker_set_auto_update_leds(PSMoveTracker *self,PSMove *move,int auto_update_leds){
        psmove_tracker_set_auto_update_leds(self, move, auto_update_leds);
    }
SWIGINTERN int PSMoveTracker_get_auto_update_leds(PSMoveTracker *self,PSMove *move){
        return psmove_tracker_get_auto_update_leds(self, move);
    }
SWIGINTERN int PSMoveTracker_set_camera_color(PSMoveTracker *self,PSMove *move,unsigned char r,unsigned char g,unsigned char b){
        return psmove_tracker_set_camera_color(self, move, r, g, b);
    }
SWIGINTERN void PSMoveTracker_enable_deinterlace(PSMoveTracker *self,int enabled){
        psmove_tracker_enable_deinterlace(self,
            enabled?PSMove_True:PSMove_False);
    }
SWIGINTERN void PSMoveTracker_set_mirror(PSMoveTracker *self,int enabled){
        psmove_tracker_set_mirror(self,
            enabled?PSMove_True:PSMove_False);
    }
SWIGINTERN int PSMoveTracker_get_mirror(PSMoveTracker *self){
        return psmove_tracker_get_mirror(self);
    }
SWIGINTERN enum PSMoveTracker_Status PSMoveTracker_get_status(PSMoveTracker *self,PSMove *move){
        return psmove_tracker_get_status(self, move);
    }
SWIGINTERN void PSMoveTracker_update_image(PSMoveTracker *self){
        return psmove_tracker_update_image(self);
    }
SWIGINTERN int PSMoveTracker_update__SWIG_0(PSMoveTracker *self){
        return psmove_tracker_update(self, NULL);
    }
SWIGINTERN int PSMoveTracker_update__SWIG_1(PSMoveTracker *self,PSMove *move){
        return psmove_tracker_update(self, move);
    }
SWIGINTERN PSMoveTrackerRGBImage PSMoveTracker_get_image(PSMoveTracker *self){
        return psmove_tracker_get_image(self);
    }
SWIGINTERN float PSMoveTracker_distance_from_radius(PSMoveTracker *self,float radius){
        return psmove_tracker_distance_from_radius(self, radius);
    }
SWIGINTERN void PSMoveTracker_set_distance_parameters(PSMoveTracker *self,float height,float center,float hwhm,float shape){
        psmove_tracker_set_distance_parameters(self, height,
            center, hwhm, shape);
    }
SWIGINTERN void delete_PSMoveTracker(PSMoveTracker *self){
        psmove_tracker_free(self);
    }
SWIGINTERN PSMoveFusion *new_PSMoveFusion(PSMoveTracker *tracker,float z_near,float z_far){
        return psmove_fusion_new(tracker, z_near, z_far);
    }
SWIGINTERN void delete_PSMoveFusion(PSMoveFusion *self){
        psmove_fusion_free(self);
    }
SWIGINTERN PSMoveMatrix4x4 PSMoveFusion_get_projection_matrix(PSMoveFusion *self){
        PSMoveMatrix4x4 tmp;
        float *matrix = psmove_fusion_get_projection_matrix(self);
        memcpy(&tmp, matrix, sizeof(tmp));
        return tmp;
    }
SWIGINTERN PSMoveMatrix4x4 PSMoveFusion_get_modelview_matrix(PSMoveFusion *self,PSMove *move){
        PSMoveMatrix4x4 tmp;
        float *matrix = psmove_fusion_get_modelview_matrix(self, move);
        memcpy(&tmp, matrix, sizeof(tmp));
        return tmp;
    }


void
PSMove_get_accelerometer_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_accelerometer_frame(move, frame, x, y, z);
}

void
PSMove_get_gyroscope_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_gyroscope_frame(move, frame, x, y, z);
}

void
PSMove_get_magnetometer_vector(PSMove *move, float *x, float *y, float *z)
{
    psmove_get_magnetometer_vector(move, x, y, z);
}

void
PSMove_get_orientation(PSMove *move, float *w, float *x, float *y, float *z)
{
    psmove_get_orientation(move, w, x, y, z);
}

void
PSMove_get_button_events(PSMove *move,
    unsigned int *pressed, unsigned int *released)
{
    psmove_get_button_events(move, pressed, released);
}

int
PSMove_connection_type_get(PSMove *move) {
    return psmove_connection_type(move);
}

int
PSMove_ax_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_ay_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_az_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, NULL, &result);
    return result;
}

int
PSMove_gx_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, &result, NULL, NULL);
    return result;
}

int
PSMove_gy_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, &result, NULL);
    return result;
}

int
PSMove_gz_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, NULL, &result);
    return result;
}


int
PSMove_mx_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_my_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_mz_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, NULL, &result);
    return result;
}

int
init(enum PSMove_Version version)
{
    return psmove_init(version);
}

void set_remote_config(enum PSMove_RemoteConfig config)
{
    return psmove_set_remote_config(config);
}

int count_connected()
{
    return psmove_count_connected();
}

void reinit()
{
    return psmove_reinit();
}

#ifdef PSMOVE_BUILD_TRACKER

int
PSMoveTrackerRGBImage_size_get(PSMoveTrackerRGBImage *image)
{
    return 3 * image->width * image->height;
}

float
PSMoveTracker_dimming_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_dimming(tracker);
}

void
PSMoveTracker_dimming_set(PSMoveTracker *tracker, float dimming)
{
    psmove_tracker_set_dimming(tracker, dimming);
}

void
PSMoveTracker_exposure_set(PSMoveTracker *tracker,
    enum PSMoveTracker_Exposure exposure)
{
    psmove_tracker_set_exposure(tracker, exposure);
}

enum PSMoveTracker_Exposure
PSMoveTracker_exposure_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_exposure(tracker);
}

void
PSMoveTracker_get_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_camera_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_camera_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_position(PSMoveTracker *tracker, PSMove *move,
    float *x, float *y, float *radius)
{
    psmove_tracker_get_position(tracker, move, x, y, radius);
}

void
PSMoveTracker_get_size(PSMoveTracker *tracker, int *width, int *height)
{
    return psmove_tracker_get_size(tracker, width, height);
}

void
PSMoveFusion_get_position(PSMoveFusion *fusion, PSMove *move,
            float *x, float *y, float *z)
{
    psmove_fusion_get_position(fusion, move, x, y, z);
}

#endif /* PSMOVE_BUILD_TRACKER */



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_psmove_init(int jarg1) {
  int jresult ;
  enum PSMove_Version arg1 ;
  enum PSMove_Bool result;
  
  arg1 = (enum PSMove_Version)jarg1; 
  result = (enum PSMove_Bool)psmove_init(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_set_remote_config(int jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  psmove_set_remote_config(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_count_connected() {
  int jresult ;
  int result;
  
  result = (int)psmove_count_connected();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_connect() {
  void * jresult ;
  PSMove *result = 0 ;
  
  result = (PSMove *)psmove_connect();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_connect_by_id(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMove *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMove *)psmove_connect_by_id(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_connection_type(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Connection_Type result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Connection_Type)psmove_connection_type(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_is_remote(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_is_remote(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_psmove_get_serial(void * jarg1) {
  char * jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  arg1 = (PSMove *)jarg1; 
  result = (char *)psmove_get_serial(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_pair(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_pair(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_pair_custom(void * jarg1, char * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (enum PSMove_Bool)psmove_pair_custom(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_set_rate_limiting(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_set_leds(void * jarg1, unsigned char jarg2, unsigned char jarg3, unsigned char jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned char)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  psmove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_set_rumble(void * jarg1, unsigned char jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned char)jarg2; 
  psmove_set_rumble(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_update_leds(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Update_Result result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Update_Result)psmove_update_leds(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_poll(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)psmove_poll(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_psmove_get_buttons(void * jarg1) {
  unsigned int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (unsigned int)psmove_get_buttons(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_button_events(void * jarg1, void * jarg2, void * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned int *)jarg2; 
  arg3 = (unsigned int *)jarg3; 
  psmove_get_button_events(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_get_battery(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Battery_Level result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Battery_Level)psmove_get_battery(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_get_temperature(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)psmove_get_temperature(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_psmove_get_temperature_in_celsius(void * jarg1) {
  float jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  arg1 = (PSMove *)jarg1; 
  result = (float)psmove_get_temperature_in_celsius(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_psmove_get_trigger(void * jarg1) {
  unsigned char jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char result;
  
  arg1 = (PSMove *)jarg1; 
  result = (unsigned char)psmove_get_trigger(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_accelerometer(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_accelerometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_gyroscope(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_gyroscope(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_magnetometer(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_magnetometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_accelerometer_frame(void * jarg1, int jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_gyroscope_frame(void * jarg1, int jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_magnetometer_vector(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  psmove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_has_calibration(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_has_calibration(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_dump_calibration(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_dump_calibration(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_enable_orientation(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_enable_orientation(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_has_orientation(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_has_orientation(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_get_orientation(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_orientation(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_reset_orientation(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_reset_orientation(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_reset_magnetometer_calibration(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_reset_magnetometer_calibration(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_save_magnetometer_calibration(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_save_magnetometer_calibration(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_get_magnetometer_calibration_range(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)psmove_get_magnetometer_calibration_range(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_disconnect(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_disconnect(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_reinit() {
  psmove_reinit();
}


SWIGEXPORT long SWIGSTDCALL CSharp_psmove_util_get_ticks() {
  long jresult ;
  long result;
  
  result = (long)psmove_util_get_ticks();
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_psmove_util_get_data_dir() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)psmove_util_get_data_dir();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_psmove_util_get_file_path(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)psmove_util_get_file_path((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_util_get_env_int(char * jarg1) {
  int jresult ;
  char *arg1 = (char *) 0 ;
  int result;
  
  arg1 = (char *)jarg1; 
  result = (int)psmove_util_get_env_int((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_psmove_util_get_env_string(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)psmove_util_get_env_string((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_connection_type_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_connection_type_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_ax_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_ax_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_ay_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_ay_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_az_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_az_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_gx_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gx_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_gy_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gy_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_gz_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gz_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_mx_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_mx_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_my_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_my_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_mz_get(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_mz_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMove__SWIG_0() {
  void * jresult ;
  PSMove *result = 0 ;
  
  result = (PSMove *)new_PSMove__SWIG_0();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMove__SWIG_1(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMove *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMove *)new_PSMove__SWIG_1(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_get_accelerometer_frame(void * jarg1, int jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_get_gyroscope_frame(void * jarg1, int jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_get_magnetometer_vector(void * jarg1, float * jarg2, float * jarg3, float * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  PSMove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_enable_orientation(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_enable_orientation(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_has_orientation(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_has_orientation(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_has_calibration(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_has_calibration(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_get_orientation(void * jarg1, float * jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_orientation(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_reset_orientation(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  PSMove_reset_orientation(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_set_leds(void * jarg1, int jarg2, int jarg3, int jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  PSMove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_set_rumble(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rumble(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_update_leds(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_update_leds(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_set_rate_limiting(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_pair(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_pair(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_pair_custom(void * jarg1, char * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)PSMove_pair_custom(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMove_get_serial(void * jarg1) {
  char * jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  arg1 = (PSMove *)jarg1; 
  result = (char *)PSMove_get_serial(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_is_remote(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_is_remote(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_poll(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_poll(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_get_buttons(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_buttons(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMove_get_button_events(void * jarg1, unsigned int * jarg2, unsigned int * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned int *)jarg2; 
  arg3 = (unsigned int *)jarg3; 
  PSMove_get_button_events(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_get_battery(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_battery(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_get_temperature(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_temperature(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PSMove_get_temperature_in_celsius(void * jarg1) {
  float jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  arg1 = (PSMove *)jarg1; 
  result = (float)PSMove_get_temperature_in_celsius(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMove_get_trigger(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_trigger(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PSMove(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  delete_PSMove(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMOVE_TRACKER_DEFAULT_WIDTH_get() {
  int jresult ;
  int result;
  
  result = (int)(640);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMOVE_TRACKER_DEFAULT_HEIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)(480);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMOVE_TRACKER_MAX_CONTROLLERS_get() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_CAMERA_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_CAMERA");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_FILENAME_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_FILENAME");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_ROI_SIZE_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_ROI_SIZE");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_COLOR_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_COLOR");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_WIDTH_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_WIDTH");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_PSMOVE_TRACKER_HEIGHT_ENV_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("PSMOVE_TRACKER_HEIGHT");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_data_set(void * jarg1, void * jarg2) {
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  arg2 = (void *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_data_get(void * jarg1) {
  void * jresult ;
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  void *result = 0 ;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  result = (void *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_width_set(void * jarg1, int jarg2) {
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  int arg2 ;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_width_get(void * jarg1) {
  int jresult ;
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  int result;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  result = (int) ((arg1)->width);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_height_set(void * jarg1, int jarg2) {
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  int arg2 ;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_height_get(void * jarg1) {
  int jresult ;
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  int result;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  result = (int) ((arg1)->height);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTrackerRGBImage_size_get(void * jarg1) {
  int jresult ;
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  int result;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  result = (int)PSMoveTrackerRGBImage_size_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMoveTrackerRGBImage() {
  void * jresult ;
  PSMoveTrackerRGBImage *result = 0 ;
  
  result = (PSMoveTrackerRGBImage *)calloc(1, sizeof(PSMoveTrackerRGBImage));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PSMoveTrackerRGBImage(void * jarg1) {
  PSMoveTrackerRGBImage *arg1 = (PSMoveTrackerRGBImage *) 0 ;
  
  arg1 = (PSMoveTrackerRGBImage *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_tracker_new() {
  void * jresult ;
  PSMoveTracker *result = 0 ;
  
  result = (PSMoveTracker *)psmove_tracker_new();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_tracker_new_with_camera(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMoveTracker *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMoveTracker *)psmove_tracker_new_with_camera(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_set_auto_update_leds(void * jarg1, void * jarg2, int jarg3) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMove_Bool arg3 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (enum PSMove_Bool)jarg3; 
  psmove_tracker_set_auto_update_leds(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_auto_update_leds(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (enum PSMove_Bool)psmove_tracker_get_auto_update_leds(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_set_dimming(void * jarg1, float jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  psmove_tracker_set_dimming(arg1,arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_psmove_tracker_get_dimming(void * jarg1) {
  float jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (float)psmove_tracker_get_dimming(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_set_exposure(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMoveTracker_Exposure arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (enum PSMoveTracker_Exposure)jarg2; 
  psmove_tracker_set_exposure(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_exposure(void * jarg1) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMoveTracker_Exposure result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (enum PSMoveTracker_Exposure)psmove_tracker_get_exposure(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_enable_deinterlace(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_tracker_enable_deinterlace(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_set_mirror(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_tracker_set_mirror(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_mirror(void * jarg1) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (enum PSMove_Bool)psmove_tracker_get_mirror(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_enable(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (enum PSMoveTracker_Status)psmove_tracker_enable(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_enable_with_color(void * jarg1, void * jarg2, unsigned char jarg3, unsigned char jarg4, unsigned char jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  unsigned char arg5 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  arg5 = (unsigned char)jarg5; 
  result = (enum PSMoveTracker_Status)psmove_tracker_enable_with_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_disable(void * jarg1, void * jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  psmove_tracker_disable(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_color(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char *)jarg3; 
  arg4 = (unsigned char *)jarg4; 
  arg5 = (unsigned char *)jarg5; 
  result = (int)psmove_tracker_get_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_camera_color(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char *)jarg3; 
  arg4 = (unsigned char *)jarg4; 
  arg5 = (unsigned char *)jarg5; 
  result = (int)psmove_tracker_get_camera_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_set_camera_color(void * jarg1, void * jarg2, unsigned char jarg3, unsigned char jarg4, unsigned char jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  unsigned char arg5 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  arg5 = (unsigned char)jarg5; 
  result = (int)psmove_tracker_set_camera_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_status(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (enum PSMoveTracker_Status)psmove_tracker_get_status(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_update_image(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  psmove_tracker_update_image(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_update(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (int)psmove_tracker_update(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_annotate(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  psmove_tracker_annotate(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_tracker_get_frame(void * jarg1) {
  void * jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  void *result = 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (void *)psmove_tracker_get_frame(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_tracker_get_image(void * jarg1) {
  void * jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMoveTrackerRGBImage result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = psmove_tracker_get_image(arg1);
  {
    PSMoveTrackerRGBImage * resultptr = (PSMoveTrackerRGBImage *) malloc(sizeof(PSMoveTrackerRGBImage));
    memmove(resultptr, &result, sizeof(PSMoveTrackerRGBImage));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_psmove_tracker_get_position(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  result = (int)psmove_tracker_get_position(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_get_size(void * jarg1, void * jarg2, void * jarg3) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  psmove_tracker_get_size(arg1,arg2,arg3);
}


SWIGEXPORT float SWIGSTDCALL CSharp_psmove_tracker_distance_from_radius(void * jarg1, float jarg2) {
  float jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  result = (float)psmove_tracker_distance_from_radius(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_set_distance_parameters(void * jarg1, float jarg2, float jarg3, float jarg4, float jarg5) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  psmove_tracker_set_distance_parameters(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_tracker_free(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  psmove_tracker_free(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSEYE_FOV_BLUE_DOT_get() {
  int jresult ;
  int result;
  
  result = (int)(75);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSEYE_FOV_RED_DOT_get() {
  int jresult ;
  int result;
  
  result = (int)(56);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveMatrix4x4_m_set(void * jarg1, void * jarg2) {
  PSMoveMatrix4x4 *arg1 = (PSMoveMatrix4x4 *) 0 ;
  float *arg2 ;
  
  arg1 = (PSMoveMatrix4x4 *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->m;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PSMoveMatrix4x4_m_get(void * jarg1) {
  void * jresult ;
  PSMoveMatrix4x4 *arg1 = (PSMoveMatrix4x4 *) 0 ;
  float *result = 0 ;
  
  arg1 = (PSMoveMatrix4x4 *)jarg1; 
  result = (float *)(float *) ((arg1)->m);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_PSMoveMatrix4x4_at(void * jarg1, int jarg2) {
  float jresult ;
  PSMoveMatrix4x4 *arg1 = (PSMoveMatrix4x4 *) 0 ;
  int arg2 ;
  float result;
  
  arg1 = (PSMoveMatrix4x4 *)jarg1; 
  arg2 = (int)jarg2; 
  result = (float)PSMoveMatrix4x4_at(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMoveMatrix4x4() {
  void * jresult ;
  PSMoveMatrix4x4 *result = 0 ;
  
  result = (PSMoveMatrix4x4 *)calloc(1, sizeof(PSMoveMatrix4x4));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PSMoveMatrix4x4(void * jarg1) {
  PSMoveMatrix4x4 *arg1 = (PSMoveMatrix4x4 *) 0 ;
  
  arg1 = (PSMoveMatrix4x4 *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_fusion_new(void * jarg1, float jarg2, float jarg3) {
  void * jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float arg3 ;
  PSMoveFusion *result = 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (PSMoveFusion *)psmove_fusion_new(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_fusion_get_projection_matrix(void * jarg1) {
  void * jresult ;
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  float *result = 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  result = (float *)psmove_fusion_get_projection_matrix(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_psmove_fusion_get_modelview_matrix(void * jarg1, void * jarg2) {
  void * jresult ;
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  float *result = 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (float *)psmove_fusion_get_modelview_matrix(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_fusion_get_position(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_fusion_get_position(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_psmove_fusion_free(void * jarg1) {
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  psmove_fusion_free(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_dimming_set(void * jarg1, float jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  PSMoveTracker_dimming_set(arg1,arg2);
}


SWIGEXPORT float SWIGSTDCALL CSharp_PSMoveTracker_dimming_get(void * jarg1) {
  float jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (float)PSMoveTracker_dimming_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_exposure_set(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMoveTracker_Exposure arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (enum PSMoveTracker_Exposure)jarg2; 
  PSMoveTracker_exposure_set(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_exposure_get(void * jarg1) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  enum PSMoveTracker_Exposure result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (enum PSMoveTracker_Exposure)PSMoveTracker_exposure_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMoveTracker__SWIG_0() {
  void * jresult ;
  PSMoveTracker *result = 0 ;
  
  result = (PSMoveTracker *)new_PSMoveTracker__SWIG_0();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMoveTracker__SWIG_1(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMoveTracker *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMoveTracker *)new_PSMoveTracker__SWIG_1(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_enable(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (enum PSMoveTracker_Status)PSMoveTracker_enable(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_enable_with_color(void * jarg1, void * jarg2, int jarg3, int jarg4, int jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  result = (enum PSMoveTracker_Status)PSMoveTracker_enable_with_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_annotate(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  PSMoveTracker_annotate(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_disable(void * jarg1, void * jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  PSMoveTracker_disable(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_set_auto_update_leds(void * jarg1, void * jarg2, int jarg3) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  int arg3 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (int)jarg3; 
  PSMoveTracker_set_auto_update_leds(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_get_auto_update_leds(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (int)PSMoveTracker_get_auto_update_leds(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_get_color(void * jarg1, void * jarg2, unsigned char * jarg3, unsigned char * jarg4, unsigned char * jarg5) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char *)jarg3; 
  arg4 = (unsigned char *)jarg4; 
  arg5 = (unsigned char *)jarg5; 
  PSMoveTracker_get_color(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_get_camera_color(void * jarg1, void * jarg2, unsigned char * jarg3, unsigned char * jarg4, unsigned char * jarg5) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char *)jarg3; 
  arg4 = (unsigned char *)jarg4; 
  arg5 = (unsigned char *)jarg5; 
  PSMoveTracker_get_camera_color(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_set_camera_color(void * jarg1, void * jarg2, unsigned char jarg3, unsigned char jarg4, unsigned char jarg5) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  unsigned char arg5 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  arg5 = (unsigned char)jarg5; 
  result = (int)PSMoveTracker_set_camera_color(arg1,arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_enable_deinterlace(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (int)jarg2; 
  PSMoveTracker_enable_deinterlace(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_set_mirror(void * jarg1, int jarg2) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int arg2 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (int)jarg2; 
  PSMoveTracker_set_mirror(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_get_mirror(void * jarg1) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (int)PSMoveTracker_get_mirror(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_get_status(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  enum PSMoveTracker_Status result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (enum PSMoveTracker_Status)PSMoveTracker_get_status(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_update_image(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  PSMoveTracker_update_image(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_update__SWIG_0(void * jarg1) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = (int)PSMoveTracker_update__SWIG_0(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_PSMoveTracker_update__SWIG_1(void * jarg1, void * jarg2) {
  int jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = (int)PSMoveTracker_update__SWIG_1(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PSMoveTracker_get_image(void * jarg1) {
  void * jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMoveTrackerRGBImage result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  result = PSMoveTracker_get_image(arg1);
  {
    PSMoveTrackerRGBImage * resultptr = (PSMoveTrackerRGBImage *) malloc(sizeof(PSMoveTrackerRGBImage));
    memmove(resultptr, &result, sizeof(PSMoveTrackerRGBImage));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_get_position(void * jarg1, void * jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMoveTracker_get_position(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_get_size(void * jarg1, int * jarg2, int * jarg3) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  PSMoveTracker_get_size(arg1,arg2,arg3);
}


SWIGEXPORT float SWIGSTDCALL CSharp_PSMoveTracker_distance_from_radius(void * jarg1, float jarg2) {
  float jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float result;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  result = (float)PSMoveTracker_distance_from_radius(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveTracker_set_distance_parameters(void * jarg1, float jarg2, float jarg3, float jarg4, float jarg5) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = (float)jarg5; 
  PSMoveTracker_set_distance_parameters(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PSMoveTracker(void * jarg1) {
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  delete_PSMoveTracker(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_PSMoveFusion(void * jarg1, float jarg2, float jarg3) {
  void * jresult ;
  PSMoveTracker *arg1 = (PSMoveTracker *) 0 ;
  float arg2 ;
  float arg3 ;
  PSMoveFusion *result = 0 ;
  
  arg1 = (PSMoveTracker *)jarg1; 
  arg2 = (float)jarg2; 
  arg3 = (float)jarg3; 
  result = (PSMoveFusion *)new_PSMoveFusion(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_PSMoveFusion(void * jarg1) {
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  delete_PSMoveFusion(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_PSMoveFusion_get_position(void * jarg1, void * jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMoveFusion *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMoveFusion_get_position(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PSMoveFusion_get_projection_matrix(void * jarg1) {
  void * jresult ;
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  PSMoveMatrix4x4 result;
  
  arg1 = (PSMoveFusion *)jarg1; 
  result = PSMoveFusion_get_projection_matrix(arg1);
  {
    PSMoveMatrix4x4 * resultptr = (PSMoveMatrix4x4 *) malloc(sizeof(PSMoveMatrix4x4));
    memmove(resultptr, &result, sizeof(PSMoveMatrix4x4));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_PSMoveFusion_get_modelview_matrix(void * jarg1, void * jarg2) {
  void * jresult ;
  PSMoveFusion *arg1 = (PSMoveFusion *) 0 ;
  PSMove *arg2 = (PSMove *) 0 ;
  PSMoveMatrix4x4 result;
  
  arg1 = (PSMoveFusion *)jarg1; 
  arg2 = (PSMove *)jarg2; 
  result = PSMoveFusion_get_modelview_matrix(arg1,arg2);
  {
    PSMoveMatrix4x4 * resultptr = (PSMoveMatrix4x4 *) malloc(sizeof(PSMoveMatrix4x4));
    memmove(resultptr, &result, sizeof(PSMoveMatrix4x4));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_init(int jarg1) {
  int jresult ;
  enum PSMove_Version arg1 ;
  int result;
  
  arg1 = (enum PSMove_Version)jarg1; 
  result = (int)init(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_set_remote_config(int jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  set_remote_config(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_count_connected() {
  int jresult ;
  int result;
  
  result = (int)count_connected();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_reinit() {
  reinit();
}


#ifdef __cplusplus
}
#endif

