/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace io.thp.psmove {

public enum Button {
  Btn_TRIANGLE = 1 << 0x04,
  Btn_CIRCLE = 1 << 0x05,
  Btn_CROSS = 1 << 0x06,
  Btn_SQUARE = 1 << 0x07,
  Btn_SELECT = 1 << 0x08,
  Btn_START = 1 << 0x0B,
  Btn_MOVE = 1 << 0x13,
  Btn_T = 1 << 0x14,
  Btn_PS = 1 << 0x10
}

}
