
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class Camera
	{
		private global::Gtk.Image cameraImage;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.Camera
			this.Name = "Gtk.Camera";
			this.Title = global::Mono.Unix.Catalog.GetString ("Camera");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Gtk.Camera.Gtk.Container+ContainerChild
			this.cameraImage = new global::Gtk.Image ();
			this.cameraImage.Name = "cameraImage";
			this.Add (this.cameraImage);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
