
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk
{
	public partial class ColorPicker
	{
		private global::Gtk.ColorSelection colorselection1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.ColorPicker
			this.Name = "Gtk.ColorPicker";
			this.Title = global::Mono.Unix.Catalog.GetString ("ColorPicker");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Gtk.ColorPicker.Gtk.Container+ContainerChild
			this.colorselection1 = new global::Gtk.ColorSelection ();
			this.colorselection1.Name = "colorselection1";
			this.colorselection1.HasPalette = true;
			this.colorselection1.HasOpacityControl = true;
			this.Add (this.colorselection1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 521;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
